### ISSUE TITLE
Escape character fails in sqlite3

### ISSUE THREAD

**Issue by marysue** [learn-co-curriculum/sqlite-data-types#11]
Typing "Lil\' Bub" gives me Error: near line 1: near ""Lil\' Bub"": syntax error.

If I type "Lil'' Bub" it works.

Using ' as an escape for a ' character seems to work.

**Comment by jenmyers** [comment]
Hi there,

This lesson is intended as a reading, not a lab, so the information here is presented as context.

As always, thanks for contributing! 💙
