### ISSUE TITLE
Link provided does not work

### ISSUE THREAD

**Issue by lorena57** [learn-co-curriculum/sqlite-data-types#12]
In the Bonus: Note on SQLite the link provided does not work,  I get the following message: This page isn’t workingwww.sqlite.org didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by sgharms** [comment]
I just tried that site and it worked. I think the issue was transient. Thanks for letting us know, though.

![image](https://user-images.githubusercontent.com/50019/66840444-0bfe5300-ef36-11e9-8e7c-39015545137a.png)
