### ISSUE TITLE
Change 'dogs' to 'cats'

### ISSUE THREAD

**Issue by mmmeyers** [learn-co-curriculum/sqlite-data-types#8]
Tried to send this as an Edit but it didn't send the right thing.
Under the table of cats,  it says: 
"Did we intend age to be represented as a whole-number, a word, or a decimal? If we asked you to add up the ages of all the **dogs** you could simply convert the 'two' to 2 in your head, but your database can't do that."
I wanted to change the word 'dogs' to 'cats.'

The following paragraph, the one that starts with "Typing gives us the ability...", around the 4th line down, it says: 
"If you tried, for example, to SUM all of the **dogs** in the above table, SQLite would actually attempt to convert, or cast, their type to something it can SUM."
Also wanted to change the word 'dogs' to 'cats.'

**Comment by AnnJohn** [comment]
Thanks! Changed from "dogs" to "cats" in the places you mentioned in the Readme
